services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=mysql
      - DB_PASSWORD=1234
      - DB_NAME=ticksy-test
      - JWT_SECRET=FaaRHalqyd9mQ+Fie3AhqrigJub3OJimeXrIpPR0LE0=
      - JWT_EXPIRATION=1d
      - CORS_ORIGIN=*
      - DB_SYNCHRONIZE=true
      - DB_LOGGING=true
      - SMTP_USER=mena7akim@gmail.com
      - SMTP_PASS=dvvoljoifqctebbx
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis-password
    depends_on:
      - db

  db:
    image: mysql:9
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ticksy-test
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redis-password
volumes:
  db_data:
