services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:9
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ticksy-test
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=1234
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redis-password
volumes:
  db_data:
